apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ftps
  name: ftps-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - image: ftps
        name: ftps
        imagePullPolicy: Never
---
    apiVersion: v1
    kind: Service
    metadata:
      annotations:
        metallb.universe.tf/address-pool: ftps-ip
      labels:
        app: ftps
      name: ftps-svc
    spec:
      ports:
      - name: command-ctrl
        port: 20
        targetPort: 20
      - name: data-transfer
        port: 21
        targetPort: 21
      - name: pasv-port
        port: 30000
        targetPort: 30000
      selector:
        app: ftps
      type: LoadBalancer
