apiVersion: v1
kind: Secret
metadata:
  labels:
    app: influxdb
  name: influxdb-secret
type: Opaque
stringData:
  INFLUX_URL: http://influxdb-svc:8086
  INFLUX_USER: admin
  INFLUX_PASSWORD: pass
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: influxdb
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      volumes:
      - name: influxdb-storage
        persistentVolumeClaim:
          claimName: influxdb-claim
      containers:
      - image: influxdb
        name: influxdb
        imagePullPolicy: Never
        volumeMounts:
        - name: influxdb-storage
          mountPath: /var/lib/influxdb
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: influxdb
  name: influxdb-svc
spec:
  ports:
  - name: influxdb-access
    port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    app: influxdb
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-data
  labels:
    app: influxdb
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/influxdb-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: influxdb
  name: influxdb-claim
spec:
  selector:
    matchLabels: 
      app: influxdb
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi