apiVersion: v1
kind: Secret
metadata:
  name: ssh-secret
type: Opaque
stringData:
  SSH_USERNAME: admin
  SSH_PASSWORD: pass
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx-alpine
        envFrom:
          - secretRef:
              name: ssh-secret
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - /tmp/liveness.sh
          initialDelaySeconds: 10
          periodSeconds: 5
---
  apiVersion: v1
  kind: Service
  metadata:
    annotations:
      metallb.universe.tf/address-pool: default
    labels:
      app: nginx
    name: nginx-svc
  spec:
    ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
    - name: ssh
      port: 22
      targetPort: 22
    selector:
      app: nginx
    type: LoadBalancer