apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    tier: general
  name: read-services
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    tier: general
  name: default-serviceread
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-services
subjects:
- kind: ServiceAccount
  name: default
  namespace: default