apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: telegraf
  name: telegraf-config
data:
  telegraf.conf: |+
    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "30s"
      flush_jitter = "0s"
      hostname = ""
      omit_hostname = false
    [[outputs.influxdb]]
      database = "telegraf"
      url = "${INFLUX_URL}"
      skip_database_creation = false
      timeout = "5s"
      username = "${INFLUX_USER}"
      password = "${INFLUX_PASSWORD}"
      user_agent = "telegraf"
    [[inputs.kube_inventory]]
      url = "https://kubernetes.default.svc:443/"
      namespace = "default"
      bearer_token = "/var/run/secrets/kubernetes.io/serviceaccount/token"
      resource_include = [ "deployments", "pods" ]
      tls_ca = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
      insecure_skip_verify = false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: telegraf
  name: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      serviceAccount: telegraf-acc
      volumes:
      - name: telegraf-conf-vol
        configMap:
          name: telegraf-config
      containers:
      - image: telegraf
        name: telegraf-pod
        imagePullPolicy: Never
        envFrom:
          - secretRef:
              name: influxdb-secret
        volumeMounts:
        - name: telegraf-conf-vol
          mountPath: /etc/telegraf/telegraf.conf
          subPath: telegraf.conf
          readOnly: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: telegraf
  name: telegraf-acc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: telegraf
  creationTimestamp: null
  name: telegraf-permissions
rules:
- apiGroups:
  - apps
  - ""
  - metrics.k8s.io
  resources:
  - deployments
  - pods
  - services
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: telegraf
  name: telegraf-rbind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: telegraf-permissions
subjects:
- kind: ServiceAccount
  name: telegraf-acc
  namespace: default