apiVersion: v1
kind: Secret
metadata:
  labels:
    app: wordpress
  name: wordpress-secret
type: Opaque
stringData:
  WP_USER: "wp"
  WP_PASSWORD: "pass"
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  annotations:
    metallb.universe.tf/address-pool: default
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
  - name: wordpress-port
    port: 5050
    targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        imagePullPolicy: Never
        envFrom:
          - secretRef:
              name: mysql-secret
          - secretRef:
              name: wordpress-secret
        ports:
          - containerPort: 5050
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - /tmp/liveness.sh
          initialDelaySeconds: 60
          periodSeconds: 5
